version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/resume-analyzer
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: job-portal
      DB_USER: admin
      DB_PASSWORD: admin@1234
      JWT_SECRET_KEY: your_secret_key_here
      RESET_SECRET_KEY: your_reset_password_secret_key_here
      sender_email: alinabagwan57@gmail.com
      sender_password: wwwk cqng hqrc faom
      GOOGLE_GENAI_API_KEY: AIzaSyBN2ayJ-0ZH8NCnR5hHinNWZhV1VdGHxNc
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: job-portal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
